[package]
name = "nia_protocol_rust"
version = "0.1.0"
authors = ["mirai"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#protobuf-codegen-pure = "2.14.0"
protoc-rust = "2.14.0"
